### ISSUE TITLE
[OmniSciDB] Update feedstock-omniscidb-{cpu, cuda}

### ISSUE THREAD

**Issue by xmnlab** [Quansight/omnisci#117]

**Comment by xmnlab** [comment]
from @pearu 

> IIRC, 5.1 is blocked by arrow-cpp<0.14 and thift-cpp-0.13 requirements that conda packages cannot be used in the same environment. When omniscidb will support arrow-0.16, the issue becomes fixed.

**Comment by pearu** [comment]
Omniscidb-internal implements now arrow-0.16 support. Until 5.2 is released, this issue remains blocked.

Omniscdb 5.2 requires arrow-cpp with CUDA enabled:
https://github.com/conda-forge/arrow-cpp-feedstock/pull/123

**Comment by pearu** [comment]
Fixed by https://github.com/conda-forge/omniscidb-feedstock that replaces omniscidb-cpu/cuda.
