### ISSUE TITLE
Redo benchmarking with Ibis-OmniSci

### ISSUE THREAD

**Issue by kcpevey** [Quansight/omnisci#132]

**Comment by xmnlab** [comment]
some references:

- https://tech.marksblogg.com/omnisci-macos-macbookpro-mbp.html
- https://tech.marksblogg.com/benchmarks.html

**Comment by xmnlab** [comment]
@dharhas what story we should tell about this benchmark?

As I understood for the slack discussions:

- we should replicate the work on https://tech.marksblogg.com/omnisci-macos-macbookpro-mbp.html using ibis
- this work need to use ibis + omnisci on a macos
- we don't need to compare the results with any other backend or approach.

is there anything else I am missing?

**Comment by dharhas** [comment]
I think the story is the same as the original blogpost, i.e. omnisci lets you do very fast data science on a huge dataset and Ibis gives you a convinient Pandas like api. We don't have to follow the blog post exactly, i.e. we might want to do some more interesting type of analysis but as a first pass we can just mimic exactly.

**Comment by dharhas** [comment]
If we can aslo make it run on linux and windows that would be nice but maybe as a stage 2.

**Comment by dharhas** [comment]
This isn't really a benchmarking task, it is a `look you can do cool stuff on big data with omnisci`

**Comment by xmnlab** [comment]
I didn't have much progress in it.

**Comment by kcpevey** [comment]
I started on this, but got slowed down because there wasn't an ibis method to populate an omnisci database from csv without bringing it into memory. I started working out the proper raw SQL to do this, but its unfinished.

**Comment by xmnlab** [comment]
maybe for the data loading we can use directly `omniql`, for example:

```
cat dump.sql | omnisql -u admin -p HyperInteractive --db omnisci
```

**Comment by xmnlab** [comment]
do we still need to move this task forward?

**Comment by xmnlab** [comment]
I am closing this issue for now. but if it still necessary I will reopen that :) thanks!
