### ISSUE TITLE
Instructions for how to use the Data Science Installer

### ISSUE THREAD

**Issue by rpekrul** [Quansight/omnisci#142]
Bash instructions need to be **working by Friday** and should be in the readme of the data science installer AND the examples page.  @xmnlab Can you take this for action?

How to download and install the bash installer (open the terminal, write the commands, etc..)

- [x] If they have Anaconda and are using the Anaconda GUI (yaml)
- [x] They have conda and want to install on the command line (environment.yml)
- [x] Don't have either Anaconda or conda and need to use the bash installer.
- [x] If they have installed the Mac Preview we need to tell them how to connect to an Omnisci database from your local machine

**Comment by xmnlab** [comment]
It seems it is already done https://github.com/Quansight/omnisci-datascience-installer

Probably the README would need more updates to include the new changes. 

I will open an issue for that.
