### ISSUE TITLE
OmniSci Examples

### ISSUE THREAD

**Issue by dharhas** [Quansight/omnisci#24]
For the September Data Science Workshop

**Comment by gnestor** [comment]
I have a few questions and thoughts:

* Can we move the existing docs into a public repo?
* Each Jupyter sub-project hosts its own documentation. We use ReadTheDocs for most of them and docs of some subprojects link to docs of other subprojects. Would this make sense for OmniSci? If not, we could maintain all docs in a single "docs" repo.
* We can use mybinder to host the existing notebook in jupyterlab-omnisci and link to them from the docs. 
* Some Jupyter subprojects like ipywidgets use [nbsphinx](https://nbsphinx.readthedocs.io/en/0.4.2/) convert notebooks to docs.

**Comment by rpekrul** [comment]
@dharhas can we just add this to the main OmniSci repo?

**Comment by rpekrul** [comment]
@dharhas How are these coming along?

**Comment by kcpevey** [comment]
Duplicate issue. Closing in favor of #126
