### ISSUE TITLE
Demonstrate end to end workflow of UDF creation in python 

### ISSUE THREAD

**Issue by dharhas** [Quansight/omnisci#26]
Demonstrate end to end workflow of UDF creation in python - how to annotate it,
register it with omnisci and invoke it

**Comment by pearu** [comment]
A prototype of the demonstration exists in the form of Jupyter notebooks in rbc package.
For demonstration:
- [ ] provide pymapd based API, see issue #28 
- [ ] document, would Jupyter notebook be an appropriate format?

**Comment by pearu** [comment]
rbc [README.txt](https://github.com/xnd-project/rbc#usage) demonstrates several basic usage cases.

**Comment by pearu** [comment]
Superseded by issue #37, so closing.
