### ISSUE TITLE
Registration mechanism for python UDF

### ISSUE THREAD

**Issue by dharhas** [Quansight/omnisci#28]
Registration mechanism for python UDFs building on rbc work by Pearu

**Comment by pearu** [comment]
Current state:
- [ ] create and publish rbc conda/pip package [2-6h]
- [ ] support for using external functions in UDFs [5-15h]
- [ ] expose python UDF API via pymapd [4-12h]

**Comment by pearu** [comment]
rbc conda package: https://github.com/conda-forge/rbc-feedstock
rbc pip package: see https://github.com/xnd-project/rbc/issues/2

**Comment by pearu** [comment]
Supporting external functions in UDFs is about extending the applicability range of UDFs.

Exposing rbc to pymapd may or may not improve UX. PRO: users would need to import only pymapd that uses rbc. CON: pymapd will depend on rbc which is not really needed.

**Comment by pearu** [comment]
rbc pip package: https://pypi.org/project/rbc-project

**Comment by pearu** [comment]
Re exposing rbc via pymapd: https://github.com/omnisci/pymapd/issues/261

**Comment by pearu** [comment]
Support for external functions is not topical.
This issue is complete once rbc is exposed via pymapd.

**Comment by pearu** [comment]
Add user interface to Runtime UDF support:
https://github.com/omnisci/pymapd/pull/272 (submitted)

**Comment by pearu** [comment]
https://github.com/omnisci/pymapd/pull/272 is merged.
