### ISSUE TITLE
Jupyterhub/Omnisci Startup Config

### ISSUE THREAD

**Issue by dharhas** [Quansight/omnisci#29]
Startup configuration to allow jupyterhub to point to a local omnisci instance

**Comment by ian-r-rose** [comment]
This is the type of task that can take a pretty wide range of timescales. There is some work done by myself, as well as some deployment work done by Mike Hinchey. A relatively simple config would take ~5 hours, but once one wants more integration between the applications served (JupyterLab, Immerse) then this starts to bleed into #30 and becomes much more open-ended.

**Comment by ian-r-rose** [comment]
The omnisci cloud team now has this working. Closing as done, and we can open new issues as they arise.
