### ISSUE TITLE
Upgrade to support the version of Altair that supports VegaLite 3.0

### ISSUE THREAD

**Issue by dharhas** [Quansight/omnisci#32]
Upgrade to support the version of Altair that supports VegaLite 3.0

**Comment by ian-r-rose** [comment]
We should be pretty close to this -- the current master branch of `jupyterlab-omnisci` supports VegaLite 3.0, I think we just need to update our demo notebooks.

**Comment by saulshanabrook** [comment]
Yeah I agree. I think this will take in total 1-5 hours, accounting for possible issues and multiple people verifying that the release works.
