### ISSUE TITLE
Ibis: Current Window Function Support

### ISSUE THREAD

**Issue by dharhas** [Quansight/omnisci#33]
Land initial support for current window function impl in omnisci.

- [x] rank (~2h)
- [x] dense_rank (~2h)
- [x] row_number (~2h)
- [x] cume_dist (~2h)
- [x] lag (~2h)
- [x] first_value (~2h)
- [x] lead (~2h)
- [x] last_value (~2h)
- [x] avg (~2h)
- [x] min (~2h)
- [x] max (~2h)
- [x] count (~2h)
- [x] sum (~2h)

total: ~30h

ref: https://github.com/omnisci/mapd-core/blob/master/Tests/ExecuteTest.cpp#L14107

**Comment by xmnlab** [comment]
https://github.com/ibis-project/ibis/pull/1771

**Comment by xmnlab** [comment]
Added size: 15 for the missing operations.

**Comment by xmnlab** [comment]
WIP PR: https://github.com/ibis-project/ibis/pull/1976

Current there is an issue related to percent_rank and cume_dist operations: https://github.com/ibis-project/ibis/issues/1975

Currently, OmniSciDB stable version does support `- 1` for window operations. This PR uses a development version of OmniSciDB (`omnisci/core-os-cpu-dev:873026091ff8a12535b50ce27e08e2c95c5c01fe`).

`- 1` support for window operations should land on `OmniSciDB` on v5.0, planned for early November.

**Comment by xmnlab** [comment]
PS: I am moving percent_rank and ntile to new issues
