### ISSUE TITLE
Ibis Geotype Support

### ISSUE THREAD

**Issue by dharhas** [Quansight/omnisci#34]
Finish support for geotypes (full select support in queries for omnisci geotypes). Proof is
to test with large geo datasets within omnisci

Geometry Editors
  - [x] ST_Transform (Returns a new geometry with its coordinates transformed to a different spatial reference system.) (~3h)
  - [x] ST_SetSRID (Sets the SRID on a geometry to a particular integer value.) (~3h)

Extra
   - [x] CastToGeography (~3h)

**Comment by xmnlab** [comment]
continues the work on #21
