### ISSUE TITLE
UDF Documentation: Create additional documentation and examples for UDFs to better cater to use cases identified

### ISSUE THREAD

**Issue by dharhas** [Quansight/omnisci#37]

**Comment by pearu** [comment]
The examples are gathered in
https://github.com/xnd-project/rbc/tree/master/notebooks

Need a documentation platform.

**Comment by pearu** [comment]
Document OmniSciDB UDFs:
https://github.com/omnisci/omniscidb-internal/pull/3807

**Comment by pearu** [comment]
@rpekrul @dharhas can you push buttons on this?
The PR requires an Omnisci review and merge.

**Comment by pearu** [comment]
Since Omnisci is very slow in reviewing PRs, we can create and publish relevant documents within the RBC projects. One Omnisci thinks that some parts of it should live under Omnisci repos, then we copy the docs over.

**Comment by rpekrul** [comment]
@pearu @dharhas any action left here?

**Comment by kcpevey** [comment]
This is the list of examples on rbc

**Comment by kcpevey** [comment]
These have been incorporated into omnisci-examples repo
