### ISSUE TITLE
Integrate Intake with Omnisci

### ISSUE THREAD

**Issue by dharhas** [Quansight/omnisci#48]
The goal is to enable use of OmniSci as an end to end workflow engine/pipeline.

- [ ] Use Intake to build a data catalog of OmniSci databases
- [ ] Intake to provide larger data sources that are outside omnisci (i.e on S3, Landsat etc.
- [ ] Intake plugin for OmniSci internal data format and data catalogs
- [ ] Develop federated catalogs based on intake/yaml data sources
- [x] Add ibis container for intake sources. (See https://github.com/intake/intake/issues/347)

**Comment by ian-r-rose** [comment]
Work on item 3 begun in Quansight/intake-omnisci#2

**Comment by ian-r-rose** [comment]
Work on item 5 also begun in Quansight/intake-omnisci#2

**Comment by ian-r-rose** [comment]
Also related, upstream API changes in intake/intake-sql#6

**Comment by mpeaton** [comment]
Which Omnisci databases are referred to in Item 1?

**Comment by dharhas** [comment]
ibis intake created, new work will be  in a new issue.
