### ISSUE TITLE
Update intake-mapd

### ISSUE THREAD

**Issue by ian-r-rose** [Quansight/omnisci#51]
@pearu did some exploratory work with intake-mapd. We need to update this to work with newer versions of pymapd and intake, and prepare it for release as a package on PyPI.

**Comment by mpeaton** [comment]
Right.  I've thus far stood up a local test environment, and renamed the base class from Plugin to DataSource.  There is a TODO in the intake-mapd code regarding mapping mapd sources, and so it would seem there is some invention required on how to map Polygon and MultiPolygon types, as well as write some test code.

**Comment by ian-r-rose** [comment]
@mpeaton I have a PR open that modernizes, cleans up, and package-ifys `intake-omnisci`, care to take a look?

**Comment by mpeaton** [comment]
Is it possible to make POLYGON types map to some other data structure than STRINGLIST, maybe numpy array ?

**Comment by xmnlab** [comment]
> Is it possible to make POLYGON types map to some other data structure than STRINGLIST, maybe numpy array ?

@mpeaton not sure if it could be related but we are adding geopandas as output for geo spatial output (https://github.com/ibis-project/ibis/pull/1858)
