### ISSUE TITLE
UDTF examples in python - notebook

### ISSUE THREAD

**Issue by dharhas** [Quansight/omnisci#75]
Original issue: https://github.com/Quansight/pearu-issues/issues/18

With the current UDTF interface, RBC users need to deal with pointer values and other low-level details. See https://github.com/xnd-project/rbc/blob/00088c3416ee7b003db2d431b463998634c2433b/rbc/tests/test_omnisci_udtf.py#L118 for the current state.

TODO:
- [x] Design user-friendly UDTF interface
- [x] Implement it
- [x] Demonstrate UDTF usages in Jupyter notebooks

**Comment by kcpevey** [comment]
@kcpevey to include this in the omnisci-examples, @pearu will provide the examples.

**Comment by pearu** [comment]
An example of UDTF in a notebook:
https://github.com/xnd-project/rbc/blob/master/notebooks/rbc-omnisci-udtf-normalize.ipynb

**Comment by rpekrul** [comment]
@kcpevey Can we close this issue?
