### ISSUE TITLE
[IBIS] OmniSciDB DDL/Client Refactoring

### ISSUE THREAD

**Issue by xmnlab** [Quansight/omnisci#93]
OmniSciDB DDL/Client Refactoring

**Comment by saulshanabrook** [comment]
We talked about this and decided that [`assign`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.assign.html) makes since for the add column. In SQL this is `insert` but `insert` in pandas or ibis adds rows not columns.

**Comment by saulshanabrook** [comment]
So in omnisci these operations are for dropping, adding, and renaming columns.

**Comment by saulshanabrook** [comment]
* `drop(columns)` in ibis see https://github.com/ibis-project/ibis/blob/8dd12de317bb9deabbb7edd1d77e8c79c4d932a4/ibis/pandas/tests/test_client.py#L71 should be mapped to DROP in omnisci
* `add(columns)` should be mapped to ADD in omnisci
* `assign(columns)` should be mapped to ALTER in omnisci.

**Comment by xmnlab** [comment]
1. add_column/drop_column PR opened by `@YarShev` https://github.com/ibis-project/ibis/pull/2094
2. https://github.com/ibis-project/ibis/pull/2086 refactor OmniSciDB DDL module and add rename_table, rename_columns and rename_user methods. It also fixes some bugs

**Comment by xmnlab** [comment]
refactoring merged.
